/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Elysia Documentation
 * Development documentation
 * OpenAPI spec version: 0.0.0
 */
import {
  useInfiniteQuery,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseInfiniteQueryResult,
  DefinedUseQueryResult,
  InfiniteData,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseInfiniteQueryOptions,
  UseInfiniteQueryResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import axios from 'axios';
import type {
  AxiosError,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  GetApiDrone200Item
} from '.././model';





/**
 * @summary Get drone list
 */
export const getApiDrone = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<GetApiDrone200Item[]>> => {
    
    
    return axios.get(
      `/api/drone`,options
    );
  }




export const getGetApiDroneInfiniteQueryKey = () => {
    return [
    'infinite', `/api/drone`
    ] as const;
    }

export const getGetApiDroneQueryKey = () => {
    return [
    `/api/drone`
    ] as const;
    }

    
export const getGetApiDroneInfiniteQueryOptions = <TData = InfiniteData<Awaited<ReturnType<typeof getApiDrone>>>, TError = AxiosError<unknown>>( options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiDrone>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiDroneInfiniteQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiDrone>>> = ({ signal }) => getApiDrone({ signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn,   staleTime: 30000,  ...queryOptions} as UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiDrone>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiDroneInfiniteQueryResult = NonNullable<Awaited<ReturnType<typeof getApiDrone>>>
export type GetApiDroneInfiniteQueryError = AxiosError<unknown>


export function useGetApiDroneInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiDrone>>>, TError = AxiosError<unknown>>(
  options: { query:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiDrone>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiDrone>>,
          TError,
          Awaited<ReturnType<typeof getApiDrone>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiDroneInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiDrone>>>, TError = AxiosError<unknown>>(
  options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiDrone>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiDrone>>,
          TError,
          Awaited<ReturnType<typeof getApiDrone>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiDroneInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiDrone>>>, TError = AxiosError<unknown>>(
  options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiDrone>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get drone list
 */

export function useGetApiDroneInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiDrone>>>, TError = AxiosError<unknown>>(
  options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiDrone>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient 
 ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiDroneInfiniteQueryOptions(options)

  const query = useInfiniteQuery(queryOptions, queryClient) as  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const getGetApiDroneQueryOptions = <TData = Awaited<ReturnType<typeof getApiDrone>>, TError = AxiosError<unknown>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiDrone>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiDroneQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiDrone>>> = ({ signal }) => getApiDrone({ signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn,   staleTime: 30000,  ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiDrone>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiDroneQueryResult = NonNullable<Awaited<ReturnType<typeof getApiDrone>>>
export type GetApiDroneQueryError = AxiosError<unknown>


export function useGetApiDrone<TData = Awaited<ReturnType<typeof getApiDrone>>, TError = AxiosError<unknown>>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiDrone>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiDrone>>,
          TError,
          Awaited<ReturnType<typeof getApiDrone>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiDrone<TData = Awaited<ReturnType<typeof getApiDrone>>, TError = AxiosError<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiDrone>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiDrone>>,
          TError,
          Awaited<ReturnType<typeof getApiDrone>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiDrone<TData = Awaited<ReturnType<typeof getApiDrone>>, TError = AxiosError<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiDrone>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get drone list
 */

export function useGetApiDrone<TData = Awaited<ReturnType<typeof getApiDrone>>, TError = AxiosError<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiDrone>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiDroneQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




