/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Elysia Documentation
 * Development documentation
 * OpenAPI spec version: 0.0.0
 */
import type { DroneImageUrl } from './droneImageUrl';

export interface Drone {
  id: string;
  brand: string;
  model: string;
  fullName: string;
  imageUrl: DroneImageUrl;
  priceThb: number;
  tankCapacityL: number;
  speedMps: number;
  sprayWidthM: number;
  performanceRaiPerDay: number;
}
