/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Elysia Documentation
 * Development documentation
 * OpenAPI spec version: 0.0.0
 */
import type { GetApiDrone200ItemImageUrl } from './getApiDrone200ItemImageUrl';

export type GetApiDrone200Item = {
  id: string;
  brand: string;
  model: string;
  fullName: string;
  imageUrl: GetApiDrone200ItemImageUrl;
  priceThb: number;
  tankCapacityL: number;
  speedMps: number;
  sprayWidthM: number;
  performanceRaiPerDay: number;
};
