/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DroneRouteImport } from './routes/drone'
import { Route as IndexRouteImport } from './routes/index'

const DroneRoute = DroneRouteImport.update({
  id: '/drone',
  path: '/drone',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/drone': typeof DroneRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/drone': typeof DroneRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/drone': typeof DroneRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/drone'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/drone'
  id: '__root__' | '/' | '/drone'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DroneRoute: typeof DroneRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/drone': {
      id: '/drone'
      path: '/drone'
      fullPath: '/drone'
      preLoaderRoute: typeof DroneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DroneRoute: DroneRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
